server {
    listen 80;
    server_name _;

    location = / {
        root /usr/share/nginx/html;
        try_files /vanilla-index.html =404;
    }

    location ~ \.mjs$ {
        root /usr/share/nginx/html;
        types {
            application/javascript mjs;
        }
        try_files $uri =404;
    }

    location / {
        root   /usr/share/nginx/html;
        try_files $uri $uri/ @proxy;
    }

    location @proxy {
        root /usr/share/nginx/html;
        try_files $uri.js /vanilla-index.html =404;
    }
}
